-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 09:56:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modeler
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modeler` ;

-- -----------------------------------------------------
-- Schema modeler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modeler` DEFAULT CHARACTER SET utf8 ;
USE `modeler` ;

-- -----------------------------------------------------
-- Table `modeler`.`word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modeler`.`word` ;

CREATE TABLE IF NOT EXISTS `modeler`.`word` (
  `wor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `wor_string` VARCHAR(50) NOT NULL,
  `wor_crea` INT UNSIGNED NOT NULL DEFAULT 0,
  `wor_script` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`wor_id`),
  UNIQUE INDEX `wor_id_UNIQUE` (`wor_id` ASC) VISIBLE,
  UNIQUE INDEX `wor_string_UNIQUE` (`wor_string` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeler`.`mistake`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modeler`.`mistake` ;

CREATE TABLE IF NOT EXISTS `modeler`.`mistake` (
  `mis_string` VARCHAR(50) NOT NULL,
  `mis_frequency` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`mis_string`),
  UNIQUE INDEX `wor_string_UNIQUE` (`mis_string` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeler`.`coding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modeler`.`coding` ;

CREATE TABLE IF NOT EXISTS `modeler`.`coding` (
  `cod_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_come_from` INT UNSIGNED NULL DEFAULT NULL,
  `cod_wor_id` INT UNSIGNED NOT NULL,
  `cod_frequency` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`cod_id`),
  UNIQUE INDEX `cod_id_UNIQUE` (`cod_id` ASC) VISIBLE,
  INDEX `fk_coding_coding_idx` (`cod_come_from` ASC) VISIBLE,
  INDEX `fk_coding_word1_idx` (`cod_wor_id` ASC) VISIBLE,
  CONSTRAINT `fk_coding_coding`
    FOREIGN KEY (`cod_come_from`)
    REFERENCES `modeler`.`coding` (`cod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coding_word1`
    FOREIGN KEY (`cod_wor_id`)
    REFERENCES `modeler`.`word` (`wor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeler`.`text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modeler`.`text` ;

CREATE TABLE IF NOT EXISTS `modeler`.`text` (
  `tex_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tex_name` VARCHAR(500) NOT NULL,
  `tex_frequency` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`tex_id`),
  UNIQUE INDEX `tex_id_UNIQUE` (`tex_id` ASC) VISIBLE,
  UNIQUE INDEX `tex_name_UNIQUE` (`tex_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeler`.`phrase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modeler`.`phrase` ;

CREATE TABLE IF NOT EXISTS `modeler`.`phrase` (
  `phr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phr_phrase` VARCHAR(2000) NOT NULL,
  `phr_cod_id` INT UNSIGNED NOT NULL,
  `phr_tex_id` INT UNSIGNED NOT NULL,
  `phr_frequency` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`phr_id`),
  UNIQUE INDEX `phr_id_UNIQUE` (`phr_id` ASC) VISIBLE,
  INDEX `fk_phrase_coding1_idx` (`phr_cod_id` ASC) VISIBLE,
  INDEX `fk_phrase_text1_idx` (`phr_tex_id` ASC) VISIBLE,
  CONSTRAINT `fk_phrase_coding1`
    FOREIGN KEY (`phr_cod_id`)
    REFERENCES `modeler`.`coding` (`cod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phrase_text1`
    FOREIGN KEY (`phr_tex_id`)
    REFERENCES `modeler`.`text` (`tex_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
